name: plasma_ev
channels:
  - conda-forge
  - omfit
  - aaronkho
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - alsa-lib=1.2.8=h166bdaf_0
  - attr=2.5.1=h166bdaf_1
  - brotli=1.0.9=h166bdaf_9
  - brotli-bin=1.0.9=h166bdaf_9
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.19.1=hd590300_0
  - ca-certificates=2023.5.7=hbcca054_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.16.0=hbbf8b49_1016
  - certifi=2023.5.7=pyhd8ed1ab_0
  - click=8.1.6=unix_pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - configparser=5.3.0=pyhd8ed1ab_0
  - contourpy=1.1.0=py39h7633fee_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - dbus=1.13.6=h5008d03_3
  - expat=2.5.0=hcb278e6_1
  - filelock=3.12.2=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.41.0=py39hd1e30aa_0
  - freetype=2.12.1=hca18f0e_1
  - gettext=0.21.1=h27087fc_0
  - glib=2.76.4=hfc55251_0
  - glib-tools=2.76.4=hfc55251_0
  - gmp=6.2.1=h58526e2_0
  - gmpy2=2.1.2=py39h376b7d2_1
  - graphite2=1.3.13=h58526e2_1001
  - gst-plugins-base=1.22.3=h938bd60_1
  - gstreamer=1.22.3=h977cf35_1
  - h5py=3.9.0=nompi_py39h680ca82_101
  - harfbuzz=7.3.0=hdb3a94d_0
  - hdf5=1.14.1=nompi_h4f84152_100
  - icu=72.1=hcb278e6_0
  - importlib-resources=6.0.0=pyhd8ed1ab_1
  - importlib_resources=6.0.0=pyhd8ed1ab_1
  - jinja2=3.1.2=pyhd8ed1ab_1
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.4=py39hf939315_1
  - krb5=1.20.1=h81ceb04_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.15=haa2dc70_1
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libaec=1.0.6=hcb278e6_1
  - libblas=3.9.0=17_linux64_openblas
  - libbrotlicommon=1.0.9=h166bdaf_9
  - libbrotlidec=1.0.9=h166bdaf_9
  - libbrotlienc=1.0.9=h166bdaf_9
  - libcap=2.67=he9d0100_0
  - libcblas=3.9.0=17_linux64_openblas
  - libclang=16.0.6=default_h1cdf331_0
  - libclang13=16.0.6=default_h4d60ac6_0
  - libcups=2.3.3=h36d4200_3
  - libcurl=8.1.2=h409715c_0
  - libdeflate=1.18=h0b41bf4_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.2=h7f98852_5
  - libflac=1.4.3=h59595ed_0
  - libgcc-ng=13.1.0=he5830b7_0
  - libgcrypt=1.10.1=h166bdaf_0
  - libgfortran-ng=13.1.0=h69a702a_0
  - libgfortran5=13.1.0=h15d22d2_0
  - libglib=2.76.4=hebfc3b9_0
  - libgomp=13.1.0=he5830b7_0
  - libgpg-error=1.47=h71f35ed_0
  - libhwloc=2.9.1=nocuda_h7313eea_6
  - libiconv=1.17=h166bdaf_0
  - libjpeg-turbo=2.1.5.1=h0b41bf4_0
  - liblapack=3.9.0=17_linux64_openblas
  - libllvm16=16.0.6=h5cf9203_0
  - libnghttp2=1.52.0=h61bc06f_0
  - libnsl=2.0.0=h7f98852_0
  - libogg=1.3.4=h7f98852_1
  - libopenblas=0.3.23=pthreads_h80387f5_0
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.39=h753d276_0
  - libpq=15.3=hbcd7760_1
  - libprotobuf=3.21.12=h3eb15da_0
  - libsndfile=1.2.0=hb75c966_0
  - libsqlite=3.42.0=h2797004_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-ng=13.1.0=hfd8a6a1_0
  - libsystemd0=253=h8c4010b_1
  - libtiff=4.5.1=h8b53f26_0
  - libuuid=2.38.1=h0b41bf4_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp-base=1.3.1=hd590300_0
  - libxcb=1.15=h0b41bf4_0
  - libxkbcommon=1.5.0=h5d7e998_3
  - libxml2=2.11.4=h0d562d8_0
  - libzlib=1.2.13=hd590300_5
  - llvm-openmp=16.0.6=h4dfa4b3_0
  - lz4-c=1.9.4=hcb278e6_0
  - markupsafe=2.1.3=py39hd1e30aa_0
  - matplotlib=3.7.2=py39hf3d152e_0
  - matplotlib-base=3.7.2=py39h0126182_0
  - mkl=2022.2.1=h84fe81f_16997
  - mpc=1.3.1=hfe3b2da_0
  - mpfr=4.2.0=hb012696_0
  - mpg123=1.31.3=hcb278e6_0
  - mpmath=1.3.0=pyhd8ed1ab_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-common=8.0.33=hf1915f5_2
  - mysql-libs=8.0.33=hca2cd23_2
  - ncurses=6.4=hcb278e6_0
  - networkx=3.1=pyhd8ed1ab_0
  - nspr=4.35=h27087fc_0
  - nss=3.89=he45b914_0
  - numpy=1.25.1=py39h6183b62_0
  - openjpeg=2.5.0=hfec8fc6_2
  - openssl=3.1.1=hd590300_1
  - packaging=23.1=pyhd8ed1ab_0
  - pcre2=10.40=hc3806b6_0
  - pillow=10.0.0=py39haaeba84_0
  - pip=23.2=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - ply=3.11=py_1
  - pthread-stubs=0.4=h36c2ea0_1001
  - pulseaudio-client=16.1=hb77b528_4
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyqt=5.15.7=py39h5c7b992_3
  - pyqt5-sip=12.11.0=py39h227be39_3
  - python=3.9.16=h2782a2a_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.9=3_cp39
  - pytorch=2.0.0=cpu_py39he4d1dc0_0
  - qt-main=5.15.8=h01ceb2d_12
  - readline=8.2=h8228510_1
  - setuptools=68.0.0=pyhd8ed1ab_0
  - sip=6.7.9=py39h3d6467e_0
  - six=1.16.0=pyh6c4a22f_0
  - sleef=3.5.1=h9b69904_2
  - sympy=1.12=pypyh9d50eac_103
  - tbb=2021.9.0=hf52228f_0
  - tk=8.6.12=h27826a3_0
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tornado=6.3.2=py39hd1e30aa_0
  - tqdm=4.65.0=pyhd8ed1ab_1
  - typing_extensions=4.7.1=pyha770c72_0
  - tzdata=2023c=h71feb2d_0
  - unicodedata2=15.0.0=py39hb9d737c_0
  - wheel=0.40.0=pyhd8ed1ab_1
  - xcb-util=0.4.0=hd590300_1
  - xcb-util-image=0.4.0=h8ee46fc_1
  - xcb-util-keysyms=0.4.0=h8ee46fc_1
  - xcb-util-renderutil=0.3.9=hd590300_1
  - xcb-util-wm=0.4.1=h8ee46fc_1
  - xkeyboard-config=2.39=hd590300_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.6=h8ee46fc_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xf86vidmodeproto=2.3.1=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h166bdaf_0
  - zipp=3.16.2=pyhd8ed1ab_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.2=hfc55251_7
prefix: /home/awang/mambaforge/envs/omfit/envs/plasma_ev
